name: Deploy Angular to Elastic Beanstalk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_LOCATION: dist/angular-github-actions-amazon-s3
  ELASTIC_BEANSTALK_NAME: angular-github-ebs-app
  ELASTIC_BEANSTALK_ENV_NAME: angular-github-ebs-env

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:headless

    - name: Build
      run: npm run build -- --configuration production --output-path=dist/angular-github-actions-amazon-s3

    - name: Zip build output
      run: |
        cd ${{github.run_id}}
        zip -r ../${{github.run_id}}.zip .
#        cd dist/angular-github-actions-amazon-s3
#        zip -r ../../deploy.zip .

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v4.1.7
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Deploy
      run: |
        aws s3 cp "deploy-files/${{github.run_id}}.zip" s3://elasticbeanstalk-us-east-1-${{ secrets.AWS_ACCOUNT_ID }}/artifact/angular-github-ebs/
        aws elasticbeanstalk create-application-version --application-name $ELASTIC_BEANSTALK_NAME --version-label ${{github.run_id}} --description ${{github.run_id}} --source-bundle S3Bucket="elasticbeanstalk-us-east-1-${{ secrets.AWS_ACCOUNT_ID }}",S3Key="artifact/angular-github-ebs/${{github.run_id}}.zip"
        aws elasticbeanstalk update-environment --application-name $ELASTIC_BEANSTALK_NAME --environment-name $ELASTIC_BEANSTALK_ENV_NAME --version-label ${{github.run_id}}
        aws elasticbeanstalk wait environment-updated --application-name $ELASTIC_BEANSTALK_NAME --environment-name $ELASTIC_BEANSTALK_ENV_NAME

#    - name: Deploy to Elastic Beanstalk
#      uses: einaregilsson/beanstalk-deploy@v21
#      with:
#        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        application_name: ${{ secrets.EB_APPLICATION_NAME }}
#        environment_name: ${{ secrets.EB_ENV_NAME }}
#        region: ${{ secrets.AWS_REGION }}
#        version_label: "v-${{ github.run_number }}"
#        deployment_package: deploy.zip
        
