name: Deploy Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Create deploy.zip
        run: zip -r deploy.zip . -x ./node_modules/\*

      - name: Generate UUID for version
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 👇 New step: Check if environment exists
      - name: Ensure Elastic Beanstalk Environment Exists
        run: |
          set -e
          ENVIRONMENT_NAME="angular-github-ebs-env-v1"
          APPLICATION_NAME="angular-github-ebs-app-v1"
          REGION="us-east-1"

          echo "Checking if environment $ENVIRONMENT_NAME exists..."

          ENV_EXISTS=$(aws elasticbeanstalk describe-environments --application-name "$APPLICATION_NAME" --environment-names "$ENVIRONMENT_NAME" --region "$REGION" --query "Environments[0].Status" --output text || echo "None")

          if [ "$ENV_EXISTS" == "None" ]; then
            echo "Environment does not exist. Creating environment..."
            aws elasticbeanstalk create-environment \
              --application-name "$APPLICATION_NAME" \
              --environment-name "$ENVIRONMENT_NAME" \
              --solution-stack-name "$STACK_NAME" \
              --option-settings Namespace=aws:elasticbeanstalk:environment,OptionName=EnvironmentType,Value=SingleInstance \
              --region "$REGION"
            echo "Environment creation triggered. Waiting for it to be ready..."
            aws elasticbeanstalk wait environment-exists --application-name "$APPLICATION_NAME" --environment-names "$ENVIRONMENT_NAME" --region "$REGION"
            echo "Environment created!"
          else
            echo "Environment already exists. Continuing deployment..."
          fi

      # 🚀 Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "angular-github-ebs-app-v1"
          environment_name: "angular-github-ebs-env-v1"
          version_label: ${{ steps.generate-uuid.outputs.uuid }}
          region: "us-east-1"
          deployment_package: deploy.zip
